default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: local
    hooks:
      - id: format-check
        name: format-check
        entry: make format-check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: test-unit
        name: test-unit
        entry: make test-unit
        language: system
        pass_filenames: false
        stages: [pre-push]
