name: CI Build and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: Build with Nix
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: cristian-main
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      - name: Build with Nix
        run: |
          nix build

      - name: Nix flake checks
        run: |
          nix flake check

      - name: Test the built binary
        run: |
          ./result/bin/wire-cli --help

      - name: Enter Nix dev shell and run integration tests
        run: |
          export WIRE_BIN=./result/bin/wire-cli
          nix develop --command ./gradlew --no-daemon batsTest
        env:
          ANDROID_USER_HOME: "${{ github.workspace }}/.android"
          GRADLE_USER_HOME: "${{ github.workspace }}/.gradle"
          XDG_CACHE_HOME: "${{ github.workspace }}/.cache"
          XDG_CONFIG_HOME: "${{ github.workspace }}"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/test-results/
